import type { IncomingMessage, ServerResponse } from 'node:http';

import { DEPLOYMENT_META_STYLES, deploymentMetaMarkup } from './deployment-info.js';

export function homeHandler(req: IncomingMessage, res: ServerResponse): void {
  if (req.method !== 'GET') { res.statusCode = 405; res.setHeader('allow', 'GET'); res.end(); return; }
  res.statusCode = 200; res.setHeader('content-type', 'text/html; charset=utf-8'); res.setHeader('cache-control', 'no-store'); res.end(HTML);
}

const HTML = String.raw`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Visual Director · Projects</title><style>:root{font-family:Inter,ui-sans-serif,system-ui;color:#f5f7fa;background:#0d1117;color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#0d1117;min-height:100vh}main{max-width:1240px;margin:auto;padding:34px 28px 60px}.lede{color:#9aa7b6;max-width:720px}.status{padding:15px;border:1px solid #2b3744;border-radius:12px;background:#141b23;margin-top:22px}.error{color:#ffc0c0}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(270px,1fr));gap:16px;margin-top:22px}.card{display:block;color:inherit;text-decoration:none;background:#141b23;border:1px solid #2a3542;border-radius:16px;padding:20px;transition:transform .15s ease,border-color .15s ease}.card:hover{transform:translateY(-2px);border-color:#52677f}.titleRow{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.name{font-size:18px;font-weight:700}.badge{font-size:10px;font-weight:800;text-transform:uppercase;padding:5px 8px;border-radius:999px;border:1px solid #395067;color:#a9c2db;white-space:nowrap}.repo{font-size:12px;color:#8190a1;margin-top:10px;overflow-wrap:anywhere}.meta{display:flex;gap:10px;align-items:center;margin-top:18px;padding-top:14px;border-top:1px solid #26323e;color:#91a0b0;font-size:11px}.open{margin-left:auto;color:#c6d6e6;font-weight:650}${DEPLOYMENT_META_STYLES}</style></head><body><main><h1>Visual Director</h1><p class="lede">Choose a game project. Project discovery comes from the local catalog; repository Canon is loaded only after you open a project.</p><div id="status" class="status">Loading configured projects…</div><div id="projects" class="grid"></div>${deploymentMetaMarkup()}</main><script>const q=s=>document.querySelector(s),el=(t,c,x)=>{const n=document.createElement(t);if(c)n.className=c;if(x!==undefined)n.textContent=x;return n};fetch('/api/projects',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'Projects request failed');return d.projects}).then(projects=>{const status=q('#status'),grid=q('#projects');if(!projects.length){status.textContent='No projects are configured in the Project Catalog.';return}status.textContent=projects.length+' configured project'+(projects.length===1?'':'s')+'.';for(const p of projects){const card=el('a','card');card.href='/projects/'+encodeURIComponent(p.project_id);const titleRow=el('div','titleRow');titleRow.append(el('div','name',p.display_name),el('span','badge',p.adapter_type));card.append(titleRow,el('div','repo',p.repository));const meta=el('div','meta');meta.append(el('span','',p.ref),el('span','open','Open project →'));card.append(meta);grid.append(card)}}).catch(e=>{const s=q('#status');s.className='status error';s.textContent=e.message});</script></body></html>`;
