export const PROJECT_SHELL_STYLES = '.project-shell{display:grid;gap:12px;margin:18px 0 22px}.project-back{display:inline-block;margin-bottom:2px;text-decoration:none}.project-kicker{color:#8391a2;font-size:11px;letter-spacing:.14em;text-transform:uppercase}.project-title{margin:4px 0 0;font-size:30px;line-height:1.15}.project-context{margin:7px 0 0;color:#8997a8;font-size:12px;overflow-wrap:anywhere}.project-nav{margin:0}.project-nav a{transition:background-color .15s ease,border-color .15s ease,color .15s ease}.project-nav a:focus-visible,.project-back:focus-visible{outline:2px solid #8fb7ff;outline-offset:3px}@media(max-width:640px){.project-shell{margin-top:14px;margin-bottom:18px}.project-title{font-size:26px}}';

export function projectShellMarkup(defaultTitle: string): string {
  return `<a id="back" class="project-back" href="/">← Projects</a><header class="project-shell"><div><div class="project-kicker">Project workspace</div><h1 id="title" class="project-title">${escapeHtml(defaultTitle)}</h1><p id="project-context" class="project-context" aria-live="polite">Loading project…</p></div><nav id="nav" class="nav project-nav" aria-label="Project navigation"></nav></header>`;
}

export const PROJECT_SHELL_CLIENT_SCRIPT = String.raw`function setupProjectShell(project,current){const root='/projects/'+encodeURIComponent(project),back=document.querySelector('#back'),nav=document.querySelector('#nav');if(back){back.href='/';back.textContent='← Projects'}if(!nav)return;nav.replaceChildren();for(const [name,segment] of [['Overview',''],['Global Canon','canon'],['Anchors','anchors'],['Generations','generations'],['Assets','assets']]){const link=document.createElement('a');link.href=segment?root+'/'+segment:root;link.textContent=name;if((current==='overview'&&!segment)||(current===segment))link.setAttribute('aria-current','page');nav.append(link)}}function setProjectContext(project){const context=document.querySelector('#project-context');if(!context)return;const repositoryRef=project.repository&&project.ref?project.repository+' @ '+project.ref:project.repository||project.ref||'';context.textContent=[project.display_name,repositoryRef].filter(Boolean).join(' · ')}`;

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character] ?? character);
}
