export const PROJECT_SHELL_STYLES = '.project-shell{display:grid;gap:12px;margin:18px 0 22px}.project-back{display:inline-block;margin-bottom:2px;text-decoration:none}.project-kicker{color:#8391a2;font-size:11px;letter-spacing:.14em;text-transform:uppercase}.project-title{margin:4px 0 0;font-size:30px;line-height:1.15}.project-context{margin:7px 0 0;color:#8997a8;font-size:12px;overflow-wrap:anywhere}.project-nav{margin:0}.project-nav a{transition:background-color .15s ease,border-color .15s ease,color .15s ease}.project-nav a:focus-visible,.project-back:focus-visible{outline:2px solid #8fb7ff;outline-offset:3px}@media(max-width:640px){.project-shell{margin-top:14px;margin-bottom:18px}.project-title{font-size:26px}}';

export const PROJECT_IMAGE_PREVIEW_STYLES = '.preview-frame{position:relative;display:grid;place-items:center;aspect-ratio:4/3;overflow:hidden;background:#090c10}.preview-image{width:100%;height:100%;object-fit:contain;object-position:center;display:block}.preview-fallback{width:100%;height:100%;display:grid;align-content:center;gap:7px;padding:16px;color:#cbd5e1;background:#18212b}.preview-fallback strong{font-size:12px}.preview-path{font:10px ui-monospace,SFMono-Regular,Consolas,monospace;color:#93a4b5;overflow-wrap:anywhere}.mini .preview-frame{width:42px;height:42px;aspect-ratio:auto;flex:0 0 42px;border-radius:8px}.mini .preview-fallback{padding:4px}.mini .preview-fallback strong{font-size:8px;text-align:center}.mini .preview-fallback .preview-path{display:none}';

export function projectShellMarkup(defaultTitle: string): string {
  return `<a id="back" class="project-back" href="/">← Projects</a><header class="project-shell"><div><div class="project-kicker">Project workspace</div><h1 id="title" class="project-title">${escapeHtml(defaultTitle)}</h1><p id="project-context" class="project-context" aria-live="polite">Loading project…</p></div><nav id="nav" class="nav project-nav" aria-label="Project navigation"></nav></header>`;
}

export const PROJECT_SHELL_CLIENT_SCRIPT = String.raw`function setupProjectShell(project,current){const root='/projects/'+encodeURIComponent(project),back=document.querySelector('#back'),nav=document.querySelector('#nav');if(back){back.href='/';back.textContent='← Projects'}if(!nav)return;nav.replaceChildren();for(const [name,segment] of [['Overview',''],['Global Canon','canon'],['Anchors','anchors'],['Generations','generations'],['Assets','assets']]){const link=document.createElement('a');link.href=segment?root+'/'+segment:root;link.textContent=name;if((current==='overview'&&!segment)||(current===segment))link.setAttribute('aria-current','page');nav.append(link)}}function setProjectContext(project){const context=document.querySelector('#project-context');if(!context)return;const repositoryRef=project.repository&&project.ref?project.repository+' @ '+project.ref:project.repository||project.ref||'';context.textContent=[project.display_name,repositoryRef].filter(Boolean).join(' · ')}`;

export const PROJECT_IMAGE_PREVIEW_CLIENT_SCRIPT = String.raw`function previewFallback(message,path){const fallback=document.createElement('div');fallback.className='preview-fallback';fallback.setAttribute('role','img');fallback.setAttribute('aria-label',message+' — '+path);const title=document.createElement('strong');title.textContent=message;const location=document.createElement('span');location.className='preview-path';location.textContent=path;fallback.append(title,location);return fallback}function createImagePreview(src,path,alt){const frame=document.createElement('div');frame.className='preview-frame';if(!path){frame.append(previewFallback('Preview unavailable','No repository image path recorded.'));return frame}const img=document.createElement('img');img.className='preview-image';img.alt=alt||'Approved Anchor preview';img.loading='lazy';img.decoding='async';const fail=message=>{if(img.isConnected)img.replaceWith(previewFallback(message,path))};img.addEventListener('error',()=>fail('Preview unavailable'));img.addEventListener('load',()=>{if(!img.naturalWidth||!img.naturalHeight){fail('Preview unavailable');return}try{const canvas=document.createElement('canvas'),scale=Math.min(1,128/img.naturalWidth,128/img.naturalHeight);canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const context=canvas.getContext('2d');if(!context)return;context.drawImage(img,0,0,canvas.width,canvas.height);const pixels=context.getImageData(0,0,canvas.width,canvas.height).data;for(let i=3;i<pixels.length;i+=4)if(pixels[i]>0)return;fail('Preview unavailable: transparent asset')}catch{}});frame.append(img);img.src=src;return frame}`;

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character] ?? character);
}
