import type { IncomingMessage, ServerResponse } from 'node:http';

export default function handler(req: IncomingMessage, res: ServerResponse): void {
  if (req.method !== 'GET') {
    res.statusCode = 405;
    res.setHeader('allow', 'GET');
    res.end();
    return;
  }
  res.statusCode = 200;
  res.setHeader('content-type', 'text/html; charset=utf-8');
  res.setHeader('cache-control', 'no-store');
  res.end(HTML);
}

const HTML = String.raw`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Approved Anchor · Visual Director</title><style>
:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#f4f7fa;background:#0c1117;color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#202938,#10161e 38rem,#0b0f14 70rem);min-height:100vh}main{max-width:1180px;margin:auto;padding:28px}.back{color:#9eabbb;text-decoration:none;font-size:13px}.head{display:flex;justify-content:space-between;align-items:end;margin:22px 0 18px}.eyebrow{font-size:11px;letter-spacing:.13em;text-transform:uppercase;color:#8290a0}.title{font-size:30px;margin:5px 0 0}.badge{display:inline-block;padding:6px 9px;border:1px solid #29583b;border-radius:999px;background:#163625;color:#7de1a0;font-size:10px;font-weight:750;letter-spacing:.08em;text-transform:uppercase}.grid{display:grid;grid-template-columns:minmax(300px,.9fr) minmax(0,1.2fr);gap:18px}.card{background:#141b23;border:1px solid #293542;border-radius:16px;overflow:hidden}.preview img{width:100%;display:block;aspect-ratio:4/5;object-fit:cover;background:#090c10}.body{padding:16px}.path{font:11px ui-monospace,SFMono-Regular,Consolas,monospace;color:#8997a8;overflow-wrap:anywhere;margin-top:9px}.section{padding:16px;border-bottom:1px solid #26313d}.section:last-child{border-bottom:0}.section h2{font-size:11px;letter-spacing:.11em;text-transform:uppercase;color:#8795a5;margin:0 0 10px}.section p,.section li{font-size:13px;line-height:1.55;color:#c6ced8}.section ul{padding-left:18px;margin:8px 0}.lineage{display:grid;grid-template-columns:1fr auto 1fr auto 1fr;align-items:center;gap:8px}.node{padding:13px;border:1px solid #304052;background:#111820;border-radius:11px;font-size:12px}.arrow{color:#677588}.related{display:grid;gap:8px}.asset{padding:11px 12px;border-radius:10px;border:1px solid #293642;background:#111820}.error{padding:16px;border:1px solid #7c3434;border-radius:12px;background:#251718;color:#ffc1c1}@media(max-width:760px){main{padding:18px}.grid{grid-template-columns:1fr}.lineage{grid-template-columns:1fr}.arrow{transform:rotate(90deg);text-align:center}.head{align-items:start;flex-direction:column;gap:12px}}
</style></head><body><main><a class="back" href="/">← Project dashboard</a><div class="head"><div><div class="eyebrow">Approved visual anchor</div><h1 id="title" class="title">Loading…</h1></div><span class="badge">Current</span></div><div id="error"></div><div id="content" class="grid" hidden><article class="card preview"><img id="image" alt="Approved Anchor"><div class="body"><div id="display"></div><div id="path" class="path"></div></div></article><article class="card"><section class="section"><h2>Visual lineage</h2><div class="lineage"><div id="global" class="node"></div><div class="arrow">→</div><div id="anchor-node" class="node"></div><div class="arrow">→</div><div class="node">Generated assets</div></div></section><section class="section"><h2>Subject lock</h2><div id="subject-lock"></div></section><section class="section"><h2>Allowed changes</h2><ul id="allowed"></ul></section><section class="section"><h2>Forbidden changes</h2><ul id="forbidden"></ul></section><section class="section"><h2>Related managed assets</h2><div id="related" class="related"></div></section></article></div></main><script>
const params=new URLSearchParams(location.search),project=params.get('project_id')||'bottom-of-thirst',subject=params.get('subject_id')||'';const q=(s)=>document.querySelector(s),text=(id,v)=>{q(id).textContent=v};const asset=(path)=>'/api/asset?project_id='+encodeURIComponent(project)+'&path='+encodeURIComponent(path);const list=(id,items)=>{const target=q(id);target.replaceChildren();for(const item of items){const li=document.createElement('li');li.textContent=item;target.append(li)}};
fetch('/api/anchor-detail?project_id='+encodeURIComponent(project)+'&subject_id='+encodeURIComponent(subject),{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'Anchor detail failed');return d}).then(d=>{text('#title',d.anchor.display_name);text('#display',d.anchor.display_name);text('#path',d.anchor.path);q('#image').src=asset(d.anchor.path);text('#global',d.lineage.global_reference?.path||'Global reference unavailable');text('#anchor-node',d.anchor.display_name+'\nApproved Anchor');const sl=q('#subject-lock');for(const value of d.canon_constraints.subject_lock){const p=document.createElement('p');p.textContent=value;sl.append(p)}list('#allowed',d.canon_constraints.allowed_changes);list('#forbidden',d.canon_constraints.forbidden_changes);const related=q('#related');if(!d.lineage.related_assets.length){related.textContent='No managed generated assets are registered for this subject yet.'}else for(const a of d.lineage.related_assets){const node=document.createElement('div');node.className='asset';node.textContent=(a.asset_type||'asset')+' · '+a.status+' · '+(a.registered_path||a.candidate_path||a.asset_id);related.append(node)}q('#content').hidden=false}).catch(e=>{const node=q('#error');node.className='error';node.textContent=e.message});
</script></body></html>`;
