import type { IncomingMessage, ServerResponse } from 'node:http';

export default function handler(req: IncomingMessage, res: ServerResponse): void {
  if (req.method !== 'GET') {
    res.statusCode = 405;
    res.setHeader('allow', 'GET');
    res.end();
    return;
  }
  res.statusCode = 200;
  res.setHeader('content-type', 'text/html; charset=utf-8');
  res.setHeader('cache-control', 'no-store');
  res.end(HTML);
}

const HTML = String.raw`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Visual Director · Projects</title><style>
:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#f5f7fa;background:#0d1117;color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 25% 0,#202938,#11161e 36rem,#0b0f14 70rem);min-height:100vh}main{max-width:1240px;margin:auto;padding:34px 28px 60px}.eyebrow{font-size:12px;letter-spacing:.16em;text-transform:uppercase;color:#8b98aa}.title{font-size:34px;margin:5px 0 8px}.intro{color:#9da9b8;margin:0 0 28px}.status{padding:15px 16px;border:1px solid #2b3744;border-radius:12px;background:#141b23;color:#9eabbb}.status.error{border-color:#743a3a;color:#ffc0c0}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(270px,1fr));gap:16px;margin-top:22px}.card{display:block;color:inherit;text-decoration:none;background:#141b23;border:1px solid #2a3542;border-radius:16px;overflow:hidden;transition:transform .15s,border-color .15s}.card:hover{transform:translateY(-2px);border-color:#52677f}.thumb{width:100%;aspect-ratio:16/9;object-fit:cover;display:block;background:#0a0e13}.placeholder{aspect-ratio:16/9;display:grid;place-items:center;color:#657487;background:linear-gradient(135deg,#17202a,#10161d)}.body{padding:16px}.name{font-size:18px;font-weight:700}.repo{font:11px ui-monospace,SFMono-Regular,Consolas,monospace;color:#8190a1;margin-top:6px;overflow-wrap:anywhere}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:16px}.stat{padding:9px;border:1px solid #283542;border-radius:10px;background:#10171f;text-align:center}.value{font-size:18px;font-weight:750}.key{font-size:9px;color:#8391a2;text-transform:uppercase;letter-spacing:.07em;margin-top:2px}@media(max-width:650px){main{padding:24px 18px}.stats{grid-template-columns:repeat(2,1fr)}}
</style></head><body><main><div class="eyebrow">Multi-project visual workspace</div><h1 class="title">Visual Director</h1><p class="intro">Choose a game project. Each repository remains the source of truth for its own visual state.</p><div id="status" class="status">Loading configured projects…</div><div id="projects" class="grid"></div></main><script>
const q=s=>document.querySelector(s),el=(t,c,x)=>{const n=document.createElement(t);if(c)n.className=c;if(x!==undefined)n.textContent=x;return n};const assetUrl=(id,p)=>'/api/projects/'+encodeURIComponent(id)+'/asset?path='+encodeURIComponent(p);fetch('/api/projects',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'Projects request failed');return d.projects}).then(projects=>{const status=q('#status'),grid=q('#projects');grid.replaceChildren();if(!projects.length){status.textContent='No projects are configured in the Project Catalog.';return}status.textContent=projects.length+' configured project'+(projects.length===1?'':'s')+'.';for(const p of projects){const card=el('a','card');card.href='/projects/'+encodeURIComponent(p.project_id);if(p.thumbnail){const img=el('img','thumb');img.src=assetUrl(p.project_id,p.thumbnail);img.alt=p.display_name;card.append(img)}else card.append(el('div','placeholder','No explicit project thumbnail'));const body=el('div','body');body.append(el('div','name',p.display_name),el('div','repo',p.repository+' @ '+p.ref));const stats=el('div','stats');for(const [key,value] of [['anchors',p.anchors],['candidates',p.candidates],['jobs',p.jobs],['failed',p.failed_jobs]]){const s=el('div','stat');s.append(el('div','value',String(value)),el('div','key',key));stats.append(s)}body.append(stats);card.append(body);grid.append(card)}}).catch(e=>{const s=q('#status');s.className='status error';s.textContent=e.message});
</script></body></html>`;