import type { IncomingMessage, ServerResponse } from 'node:http';

export default function handler(req: IncomingMessage, res: ServerResponse): void {
  if (req.method !== 'GET') { res.statusCode = 405; res.setHeader('allow','GET'); res.end(); return; }
  res.statusCode = 200; res.setHeader('content-type','text/html; charset=utf-8'); res.setHeader('cache-control','no-store'); res.end(HTML);
}

const HTML = String.raw`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Project · Visual Director</title><style>
:root{font-family:Inter,ui-sans-serif,system-ui;color:#f4f7fa;background:#0c1117;color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#0c1117}main{max-width:1200px;margin:auto;padding:28px}.nav{display:flex;flex-wrap:wrap;gap:8px;margin:18px 0 24px}.nav a,.back{color:#aab5c2;text-decoration:none;border:1px solid #2d3947;border-radius:9px;padding:8px 11px}.back{border:0;padding:0}.status{padding:14px;border:1px solid #2d3947;border-radius:12px;background:#141b23}.error{color:#ffc0c0;border-color:#743a3a}.hero{display:grid;grid-template-columns:1.5fr 1fr;gap:15px;margin-top:20px}.card{background:#141b23;border:1px solid #293542;border-radius:15px;overflow:hidden}.card img{width:100%;aspect-ratio:16/9;object-fit:cover;display:block}.body{padding:14px}.anchors{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:12px}.anchor{color:inherit;text-decoration:none}.anchor img{width:100%;aspect-ratio:4/5;object-fit:cover}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.stat{padding:14px;border:1px solid #293542;border-radius:12px;background:#141b23}.value{font-size:25px;font-weight:750}.key{font-size:10px;color:#8795a5;text-transform:uppercase}.section{margin-top:26px}.empty{padding:28px;color:#7f8d9e}@media(max-width:700px){main{padding:18px}.hero{grid-template-columns:1fr}.stats{grid-template-columns:repeat(2,1fr)}}
</style></head><body><main><a class="back" href="/">← Projects</a><h1 id="title">Project</h1><div id="nav" class="nav"></div><div id="status" class="status">Loading project…</div><section class="hero"><article id="global" class="card"></article><article id="grand" class="card"></article></section><section class="section"><h2>Approved Anchors</h2><div id="anchors" class="anchors"></div></section><section class="section"><h2>Workflow</h2><div id="stats" class="stats"></div></section></main><script>
const m=location.pathname.match(/^\/projects\/([^/]+)\/?$/),project=m?decodeURIComponent(m[1]):'';const q=s=>document.querySelector(s),el=(t,c,x)=>{const n=document.createElement(t);if(c)n.className=c;if(x!==undefined)n.textContent=x;return n};if(!project)throw new Error('Project id is missing from the route.');const root='/projects/'+encodeURIComponent(project),asset=p=>'/api/projects/'+encodeURIComponent(project)+'/asset?path='+encodeURIComponent(p);for(const [label,path] of [['Overview',root],['Anchors',root+'/anchors'],['Generations',root+'/generations'],['Assets',root+'/assets']]){const a=el('a','',label);a.href=path;q('#nav').append(a)}function visual(target,item,label){target.replaceChildren();if(!item){target.append(el('div','empty','No explicit '+label+' is configured.'));return}if(item.asset_path){const img=el('img');img.src=asset(item.asset_path);img.alt=label;target.append(img)}target.append(el('div','body',label+(item.asset_path?' · '+item.asset_path:'')))}Promise.all([fetch('/api/projects',{cache:'no-store'}).then(r=>r.json()),fetch('/api/projects/'+encodeURIComponent(project)+'/overview',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'Overview request failed');return d})]).then(([catalog,o])=>{const p=catalog.projects?.find(x=>x.project_id===project);if(!p)throw new Error('Unknown project_id: '+project);q('#title').textContent=p.display_name;visual(q('#global'),o.visual_direction.global_style,'Global Visual Style');visual(q('#grand'),o.visual_direction.grand_design,'Grand Design');const anchors=q('#anchors');anchors.replaceChildren();for(const a of o.approved_anchors){const card=el('a','card anchor');card.href=root+'/anchors/'+encodeURIComponent(a.subject_id);const img=el('img');img.src=asset(a.path);img.alt=a.display_name;card.append(img,el('div','body',a.display_name));anchors.append(card)}if(!o.approved_anchors.length)anchors.append(el('div','empty','No Approved Anchors registered.'));const counts={anchors:o.approved_anchors.length,candidates:o.workflow.assets.filter(a=>a.status==='candidate').length,jobs:o.workflow.jobs.length,failed:o.workflow.jobs.filter(j=>j.status==='failed').length};for(const [k,v] of Object.entries(counts)){const s=el('div','stat');s.append(el('div','value',String(v)),el('div','key',k));q('#stats').append(s)}q('#status').textContent='Repository visual state loaded for '+p.display_name+'.'}).catch(e=>{const s=q('#status');s.className='status error';s.textContent=e.message});
</script></body></html>`;