import type { IncomingMessage, ServerResponse } from 'node:http';

export default function handler(req: IncomingMessage, res: ServerResponse): void {
  if (req.method !== 'GET') { res.statusCode = 405; res.setHeader('allow','GET'); res.end(); return; }
  res.statusCode = 200; res.setHeader('content-type','text/html; charset=utf-8'); res.setHeader('cache-control','no-store'); res.end(HTML);
}

const HTML = String.raw`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Project view · Visual Director</title><style>
:root{font-family:Inter,ui-sans-serif,system-ui;color:#f4f7fa;background:#0c1117;color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#0c1117}main{max-width:1200px;margin:auto;padding:28px}.back{color:#aab5c2;text-decoration:none}.status{padding:14px;border:1px solid #2d3947;border-radius:12px;background:#141b23;margin:18px 0}.error{color:#ffc0c0;border-color:#743a3a}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:14px}.card{background:#141b23;border:1px solid #293542;border-radius:14px;overflow:hidden}.card img{width:100%;aspect-ratio:4/3;object-fit:cover;display:block}.anchor img{aspect-ratio:4/5}.body{padding:13px}.name{font-weight:700}.meta{font-size:11px;color:#8997a8;margin-top:5px;overflow-wrap:anywhere}.badge{display:inline-block;padding:4px 7px;border:1px solid #3b4857;border-radius:999px;font-size:9px;text-transform:uppercase}.jobs{display:grid;gap:10px}.job{padding:14px;border:1px solid #293542;border-radius:12px;background:#141b23}.job.failed{border-color:#713a3a}.empty{padding:28px;border:1px dashed #34404e;border-radius:14px;color:#7d8b9d;text-align:center}@media(max-width:650px){main{padding:18px}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style></head><body><main><a id="back" class="back" href="/">← Project</a><h1 id="title">Loading…</h1><div id="status" class="status">Loading repository state…</div><div id="content"></div></main><script>
const m=location.pathname.match(/^\/projects\/([^/]+)\/(anchors|assets|generations)\/?$/),project=m?decodeURIComponent(m[1]):'',mode=m?m[2]:'';const q=s=>document.querySelector(s),el=(t,c,x)=>{const n=document.createElement(t);if(c)n.className=c;if(x!==undefined)n.textContent=x;return n};if(!project||!mode)throw new Error('Project view route is invalid.');const root='/projects/'+encodeURIComponent(project),asset=p=>'/api/projects/'+encodeURIComponent(project)+'/asset?path='+encodeURIComponent(p);q('#back').href=root;const labels={anchors:'Approved Anchors',assets:'Asset Gallery',generations:'Generation Jobs'};q('#title').textContent=labels[mode];Promise.all([fetch('/api/projects',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'Projects request failed');return d}),fetch('/api/projects/'+encodeURIComponent(project)+'/overview',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'Overview request failed');return d})]).then(([catalog,o])=>{const p=catalog.projects.find(x=>x.project_id===project);if(!p)throw new Error('Unknown project_id: '+project);q('#status').textContent=p.display_name+' · '+p.repository+' @ '+p.ref;const c=q('#content');if(mode==='anchors'){const grid=el('div','grid');for(const a of o.approved_anchors){const card=el('a','card anchor');card.href=root+'/anchors/'+encodeURIComponent(a.subject_id);card.style.color='inherit';card.style.textDecoration='none';const img=el('img');img.src=asset(a.path);img.alt=a.display_name;const body=el('div','body');body.append(el('span','badge','approved'),el('div','name',a.display_name),el('div','meta',a.path));card.append(img,body);grid.append(card)}c.append(o.approved_anchors.length?grid:el('div','empty','No Approved Anchors registered.'));return}if(mode==='generations'){const jobs=el('div','jobs');for(const j of o.workflow.jobs){const row=el('div','job'+(j.status==='failed'?' failed':''));row.append(el('div','name',j.request_text||j.job_id),el('div','meta',[j.job_id,j.asset_type,j.subject_ids.join(', '),j.generator,j.status].filter(Boolean).join(' · ')));jobs.append(row)}c.append(o.workflow.jobs.length?jobs:el('div','empty','No Generation Jobs registered.'));return}const grid=el('div','grid');for(const a of o.workflow.assets){const card=el('div','card');const pth=a.registered_path||a.candidate_path;if(pth){const img=el('img');img.src=asset(pth);img.alt=a.asset_id;card.append(img)}const body=el('div','body');body.append(el('span','badge',a.status),el('div','name',a.asset_type),el('div','meta',[a.subject_id,pth||a.asset_id].filter(Boolean).join(' · ')));card.append(body);grid.append(card)}c.append(o.workflow.assets.length?grid:el('div','empty',o.workflow.available?'No managed assets registered.':'No workflow index exists yet.'))}).catch(e=>{const s=q('#status');s.className='status error';s.textContent=e.message});
</script></body></html>`;