import type { IncomingMessage, ServerResponse } from 'node:http';

export default function handler(req: IncomingMessage, res: ServerResponse): void {
  if (req.method !== 'GET') { res.statusCode = 405; res.setHeader('allow','GET'); res.end(); return; }
  res.statusCode = 200; res.setHeader('content-type','text/html; charset=utf-8'); res.setHeader('cache-control','no-store'); res.end(HTML);
}

const HTML = String.raw`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Approved Anchor · Visual Director</title><style>
:root{font-family:Inter,ui-sans-serif,system-ui;color:#f4f7fa;background:#0c1117;color-scheme:dark}*{box-sizing:border-box}body{margin:0}main{max-width:1050px;margin:auto;padding:28px}.back{color:#aab5c2;text-decoration:none}.error{margin-top:20px;padding:14px;border:1px solid #743a3a;border-radius:12px;color:#ffc0c0}.grid{display:grid;grid-template-columns:minmax(280px,.8fr) 1.2fr;gap:18px;margin-top:20px}.card{border:1px solid #293542;border-radius:15px;background:#141b23;overflow:hidden}.card img{width:100%;aspect-ratio:4/5;object-fit:cover;display:block}.body,.section{padding:15px}.section{border-bottom:1px solid #293542}.section:last-child{border-bottom:0}.meta{font-size:12px;color:#93a0b0;overflow-wrap:anywhere}li{line-height:1.5;margin:5px 0}@media(max-width:700px){main{padding:18px}.grid{grid-template-columns:1fr}}
</style></head><body><main><a id="back" class="back">← Anchors</a><h1 id="title">Approved Anchor</h1><div id="error"></div><div id="content" class="grid" hidden><article class="card"><img id="image"><div class="body"><strong id="name"></strong><div id="path" class="meta"></div></div></article><article class="card"><div class="section"><h2>Subject lock</h2><div id="lock"></div></div><div class="section"><h2>Allowed changes</h2><ul id="allowed"></ul></div><div class="section"><h2>Forbidden changes</h2><ul id="forbidden"></ul></div><div class="section"><h2>Related assets</h2><div id="related" class="meta"></div></div></article></div></main><script>
const m=location.pathname.match(/^\/projects\/([^/]+)\/anchors\/([^/]+)\/?$/),project=m?decodeURIComponent(m[1]):'',subject=m?decodeURIComponent(m[2]):'';const q=s=>document.querySelector(s);if(!project||!subject)throw new Error('Anchor route is invalid.');const root='/projects/'+encodeURIComponent(project);q('#back').href=root+'/anchors';const asset=p=>'/api/projects/'+encodeURIComponent(project)+'/asset?path='+encodeURIComponent(p);const list=(sel,items)=>{for(const x of items){const li=document.createElement('li');li.textContent=x;q(sel).append(li)}};Promise.all([fetch('/api/projects',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'Projects request failed');return d}),fetch('/api/projects/'+encodeURIComponent(project)+'/anchor-detail?subject_id='+encodeURIComponent(subject),{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'Anchor detail failed');return d})]).then(([catalog,d])=>{if(!catalog.projects.find(x=>x.project_id===project))throw new Error('Unknown project_id: '+project);q('#title').textContent=d.anchor.display_name;q('#name').textContent=d.anchor.display_name;q('#path').textContent=d.anchor.path;q('#image').src=asset(d.anchor.path);q('#image').alt=d.anchor.display_name;for(const x of d.canon_constraints.subject_lock){const p=document.createElement('p');p.textContent=x;q('#lock').append(p)}list('#allowed',d.canon_constraints.allowed_changes);list('#forbidden',d.canon_constraints.forbidden_changes);q('#related').textContent=d.lineage.related_assets.length?d.lineage.related_assets.map(a=>(a.registered_path||a.candidate_path||a.asset_id)+' · '+a.status).join('\n'):'No related managed assets registered.';q('#content').hidden=false}).catch(e=>{const n=q('#error');n.className='error';n.textContent=e.message});
</script></body></html>`;